/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecuperarPresupuesto.java
 *
 * Created on 01/08/2015, 08:26:55 PM
 */
package winspapus.herramienta.Tabulador;

import winspapus.herramienta.presupuesto.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Betmart
 * 
 */
public class RecuperarTabulador extends javax.swing.JDialog {
    String ruta;
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    Connection conex;
    /** Creates new form RecuperarPresupuesto */
    public RecuperarTabulador(java.awt.Frame parent, boolean modal, Connection conex) {
        super(parent, modal);
        initComponents();
        this.conex = conex;
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(91, 91, 95));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Importar Tabulador");
        jLabel1.setOpaque(true);

        jLabel2.setText("Seleccione Archivo a Recuperar");

        jTextField1.setEditable(false);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winspapus/imagenes/ok.fw.png"))); // NOI18N
        okButton.setToolTipText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winspapus/imagenes/eliminar.png"))); // NOI18N
        cancelButton.setToolTipText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(390, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(okButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    public void borrartabu (String idtabu){   
            
                
            String borracap="DELETE FROM ctabs WHERE mtabus_id='"+idtabu+"' AND mtabus_id NOT IN "
                    + "(SELECT id FROM mtabus)";
            try {
                Statement st = (Statement) conex.createStatement();
                st.execute(borracap);
                String borradetmat = "DELETE FROM deptabs WHERE mtabus_id='"+idtabu+"' "
                        + "AND mtabus_id NOT IN (SELECT id FROM mtabus)";
                st.execute(borradetmat);
                String borrademano = "DELETE FROM dmoptabs WHERE mtabus_id='"+idtabu+"' "
                        + " AND mtabus_id NOT IN (SELECT id FROM mtabus)";
                st.execute(borrademano);
                String dmtabs = "DELETE FROM dmtabs WHERE mtabus_id='"+idtabu+"' AND "
                        + "mtabus_id NOT IN (SELECT id FROM mtabus)";
                st.execute(dmtabs);
                String metabs = "DELETE FROM metabs WHERE mtabus_id='"+idtabu+"' "
                        + "AND mtabus_id NOT IN (SELECT id FROM mtabus)";
                st.execute(metabs);
                String mmotabs = "DELETE FROM mmotabs WHERE mtabus_id='"+idtabu+"' "
                        + "AND mtabus_id NOT IN (SELECT id FROM mtabus)";
                st.execute(mmotabs);
                String mmtabs = "DELETE FROM mmtabs WHERE mtabus_id='"+idtabu+"'"
                        + " AND mtabus_id NOT IN (SELECT id FROM mtabus)";
                st.execute(mmtabs);
                String mptabus = "DELETE FROM mptabs WHERE mtabus_id='"+idtabu+"'"
                        + " AND mtabus_id NOT IN (SELECT id FROM mtabus)";
                st.execute(mptabus);
                String mtabus = "DELETE FROM mtabus WHERE id='"+idtabu+"'";
                st.execute(mtabus);
                JOptionPane.showMessageDialog(this, "Se ha borrado el listado de precios referencial "+idtabu);            
               }
            // TODO add your handling code here:
            catch (SQLException ex) {
                Logger.getLogger(RecuperarTabulador.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    private void ejecutar(String [] split)
    {
        String mtabu="";        
        for(int i=0;i<split.length;i++)
        {
            String trim = split[i].trim();
            trim = trim.replace(';', ' ');
            if(i==0)
            {
                mtabu=trim;
                String sql = "SELECT COUNT(*) FROM mtabus WHERE id='"+mtabu+"'";
                int contPres = 0;
                try {
                    Statement st = (Statement) conex.createStatement();
                    ResultSet rst = st.executeQuery(sql);
                    while(rst.next())
                       contPres = rst.getInt(1);
                    if(contPres>0)
                    {
                        int op = JOptionPane.showConfirmDialog(rootPane, "Tabulador Ya existe, ¿Desea modificarlo?", "Tabulador Existe", JOptionPane.YES_NO_OPTION);
                        if(op==JOptionPane.YES_OPTION)
                            borrartabu(mtabu);
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, "Recuperación de Tabulador Cancelada");
                            break;              
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(RecuperarTabulador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                try {
                    System.out.println("A recuperar "+trim);
                    Statement ex = conex.createStatement();
                    ex.execute(trim);
                    
                } catch (SQLException ex1) {
                   
                    JOptionPane.showMessageDialog(rootPane, "Error al Recuperar Tabulador "+ex1.getMessage());
                    Logger.getLogger(RecuperarTabulador.class.getName()).log(Level.SEVERE, null, ex1);break;
                }
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Se ha importado el Tabulador "+mtabu);
    }
    private void recuperarTabu()
    {
        String cad;
        String completa="";
        String [] split;
        try {
            FileReader file = new FileReader(ruta);
            BufferedReader io = new BufferedReader(file);
            try {
                while((cad = io.readLine())!=null){
                    completa=completa+cad;
                }
            } catch (IOException ex) {
                Logger.getLogger(RecuperarTabulador.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RecuperarTabulador.class.getName()).log(Level.SEVERE, null, ex);
        }
       split = completa.split(";");
       ejecutar(split);
    }
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
       jLabel3.setText("Recuperando Tabulador, puede tomar unos pocos minutos");
        recuperarTabu();
        doClose(RET_OK);
}//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
}//GEN-LAST:event_cancelButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(jTextField1);
        File fichero = fileChooser.getSelectedFile();
        jTextField1.setText(fichero.getPath().toString());
        ruta = jTextField1.getText().toString();
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
