/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RespaldarTabulador.java
 *
 * Created on 03/08/2015, 03:46:18 PM
 */
package winspapus.herramienta.Tabulador;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Betmart
 */
public class RespaldarTabulador extends javax.swing.JDialog {

    private Connection conex;
    String mtabu;
    int hilos = 11;
    StringBuffer sqlInsert = new StringBuffer();
    String ctabs="", deptabs="", dmoptabs="", dmtabs="", mbdats="", mconts="", metabs="", mmotabs="", mmtabs="", mprops="", mptabs="", mtabus="";
    /** A return status code - returned if Cancel button has been pressed */
    
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    private String ruta;

    /** Creates new form RespaldarTabulador */
    public RespaldarTabulador(java.awt.Frame parent, boolean modal, String mtabu, Connection conex) {
        super(parent, modal);
        initComponents();
        this.conex=conex;
        this.mtabu = mtabu;

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winspapus/imagenes/eliminar.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winspapus/imagenes/ok.fw.png"))); // NOI18N
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(91, 91, 95));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exportar Tabular Activo");
        jLabel1.setOpaque(true);

        jLabel2.setText("Seleccione Ruta para Exportar");

        jTextField1.setEditable(false);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jButton1))
                    .addContainerGap(139, Short.MAX_VALUE)))
        );

        getRootPane().setDefaultButton(okButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void verificaHilos()
    {
        hilos--;
        if(hilos==0)
        {
            sqlInsert.append(mtabus).append(ctabs).append(deptabs).
                    append(dmoptabs).append(dmtabs).append(mbdats).append(mconts).
                    append(metabs).append(mmotabs).append(mmtabs).append(mprops).
                    append(mptabs);
            File file = new File(ruta);
            try {
                PrintWriter print = new PrintWriter(file);
                print.write(sqlInsert.toString());
                print.close();
                JOptionPane.showMessageDialog(rootPane, "Se ha realizado el respaldo de tabulador "+mtabu+" "
                        + "en la ruta "+ruta+". Debe tomar este archivo para respaldar "
                        + "el tabulador en su otro dispositivo." );
                
             doClose(RET_OK);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(RespaldarTabulador.class.getName()).log(Level.SEVERE, null, ex);
            }
            doClose(RET_OK);
        }
    }
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(jTextField1);
        File fichero = fileChooser.getSelectedFile();
        jTextField1.setText(fichero.getPath().toString());
        ruta = jTextField1.getText().toString();
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void iniciaRespaldo()
    {
        //REPLACE INTO de mtabus
        int cont=0;
        mtabus = mtabu+";\n";
        String sql = "SELECT id, descri, vigencia, IFNULL(padyga,0) as padyga, IFNULL(pcosfin, 0) as pcosfin, "
                + "IFNULL(pimpue, 0) as pimpue, IFNULL(pprest, 0) as pprest, IFNULL(putild,0) as putild, IFNULL(status,'') as status, "
                + "IFNULL(seleccionado,0) as seleccionado, IFNULL(mcont,'') as mcont, IFNULL(mprop, '') as mprop, IFNULL(oficial,0) as oficial,"
                + "IFNULL(bloqueado,0) as bloqueado FROM mtabus WHERE id='"+mtabu+"'";
        try {
            Statement st = conex.createStatement();
            ResultSet rst = st.executeQuery(sql);
            while(rst.next())
            {
                String vigencia = rst.getString("vigencia");
                if(cont>0)
                    mtabus = mtabus+",\n";
                if(cont==0)
                    mtabus=mtabus+"REPLACE INTO mtabus (id, descri, vigencia, padyga, pcosfin, pimpue, pprest, putild, status"
                            + ",seleccionado, mcont, mprop, oficial, bloqueado) VALUES \n";
                mtabus = mtabus+"('"+rst.getString("id")+"','"+rst.getString("descri") +"',"
                        + "IF("+vigencia+" IS NULL, NULL, '"+vigencia+"'), "+rst.getString("padyga") +","
                        + ""+rst.getString("pcosfin")+", "+rst.getString("pimpue")+","
                        + ""+rst.getString("pprest")+", "+rst.getString("putild")+","
                        + "'"+rst.getString("status")+"', "+rst.getString("seleccionado") +","
                        + "'"+rst.getString("mcont")+"', '"+rst.getString("mprop")+"',"
                        + ""+rst.getString("oficial")+", "+rst.getString("bloqueado")+")";
                
                cont++;
            }
            if(cont>0)
                mtabus = mtabus+";\n";
            cont=0;
        } catch (SQLException ex) {
            Logger.getLogger(RespaldarTabulador.class.getName()).log(Level.SEVERE, null, ex);
        }
        ThreadCtab tctab = new ThreadCtab(conex, mtabu, this);
        tctab.start();
        ThreadDeptabs tdeptabs = new ThreadDeptabs(conex, mtabu, this);
        tdeptabs.start();
        ThreadDmoptabs tdmoptabs = new ThreadDmoptabs(conex, mtabu, this);
        tdmoptabs.start();
        ThreadDmtabs tdmtabs = new ThreadDmtabs(conex, mtabu, this);
        tdmtabs.start();
        ThreadMbdats tmbdats = new ThreadMbdats(conex, mtabu, this);
        tmbdats.start();
        ThreadMconts tmconts = new ThreadMconts(conex, mtabu, this);
        tmconts.start();
        ThreadMetabs tmetabs = new ThreadMetabs(conex, mtabu, this);
        tmetabs.start();
        ThreadMmotabs tmmotabs = new ThreadMmotabs(conex, mtabu, this);
        tmmotabs.start();
        ThreadMmtabs tmmtabs = new ThreadMmtabs(conex, mtabu, this);
        tmmtabs.start();
        ThreadMprops tmprops = new ThreadMprops(conex, mtabu, this);
        tmprops.start();
        ThreadMptabs tmtabs = new ThreadMptabs(conex, mtabu, this);
        tmtabs.start();        
            /*ThreadMprops tmprops = new ThreadMprops(conex, mpres, this);
            tmprops.start();*/
        
        
    }
    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        iniciaRespaldo();
        // TODO add your handling code here:
    }//GEN-LAST:event_okButtonMouseClicked
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
