/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * recalcula.java
 *
 * Created on 04/09/2013, 12:55:47 PM
 */
package winspapus;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Betmart
 */
public class recalcula extends javax.swing.JDialog {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
Connection conex;
float aumenta, dismi;
int cuenta=0;
String tabu;
    /** Creates new form recalcula */
    public recalcula(java.awt.Frame parent, boolean modal, Connection conex, String tabu) {
        super(parent, false);
        initComponents();
this.conex = conex;
this.tabu = tabu;
jLabel4.setVisible(false);
        jProgressBar1.setVisible(false);
agrupa();
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(100, 100, 100));

        jLabel1.setBackground(new java.awt.Color(91, 91, 95));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recalcular Listado de Precios Referenciales");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Opciones"));

        jRadioButton1.setText("Borrar Precios Asumidos");

        jRadioButton2.setText("Redondear Precios Unitarios a Precios Asumidos");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Igualar Precios Unitarios a Precios Asumidos");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Porcentajes Aumentar");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel2.setText("+");

        jRadioButton5.setText("Porcentajes Disminuir");

        jLabel3.setText("-");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jRadioButton6.setSelected(true);
        jRadioButton6.setText("Recalcular Precios Unitarios a Partir de APU");

        jRadioButton8.setText("Borrar todos los APU");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jRadioButton6)
                            .addGap(22, 22, 22))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton1)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jRadioButton5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jRadioButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING))))))
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winspapus/imagenes/eliminar.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winspapus/imagenes/selecc.fw.png"))); // NOI18N
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jProgressBar1.setDoubleBuffered(true);

        jLabel4.setText("Recalculando");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public final void agrupa(){
        buttonGroup1.add(jRadioButton1);
         buttonGroup1.add(jRadioButton2);
          buttonGroup1.add(jRadioButton3);
           buttonGroup1.add(jRadioButton4);
            buttonGroup1.add(jRadioButton5);
             buttonGroup1.add(jRadioButton6);
               buttonGroup1.add(jRadioButton8);
    }
    public void borraprecasu(){
        String borra = "UPDATE mptabs SET precasu=0, redondeo=0 WHERE mtabus_id='"+tabu+"' AND status=1";
        try {
            Statement str = (Statement) conex.createStatement();
            str.execute(borra);
            JOptionPane.showMessageDialog(rootPane, "Se han borrado los precios asumidos de las partidas del listado de precios");
        } catch (SQLException ex) {
            Logger.getLogger(recalcula.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void redondprecunit(){
        
        float precunit, precasu;
        String numero;
        String redondea = "SELECT precunit,numero FROM mptabs WHERE mtabus_id='"+tabu+"' AND status=1";
        try {
            Statement st = (Statement) conex.createStatement();
            ResultSet rst = st.executeQuery(redondea);
            while(rst.next()){
                precunit = rst.getFloat(1);
                precasu = (float) Math.rint(((precunit+0.000001)*100))/100;
                numero = rst.getString(2);
                String actualiza = "UPDATE mptabs SET precasu="+precasu+", redondeo=1 WHERE mtabus_id='"+tabu+"'"
                        + "AND numero="+numero+" AND status=1";
                Statement stactuliza = (Statement) conex.createStatement();
                stactuliza.execute(actualiza);
            

            }
            JOptionPane.showMessageDialog(rootPane, "Se han redondeado todos los precios unitarios del listado de precios "+tabu);
        } catch (SQLException ex) {
            Logger.getLogger(recalcula.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void precasuaprecunit(){
        float precunit, precasu;
        String numero;
        String redondea = "SELECT precasu,numero FROM mptabs WHERE mtabus_id='"+tabu+"' AND status=1";
        try {
            Statement st = (Statement) conex.createStatement();
            ResultSet rst = st.executeQuery(redondea);
            while(rst.next()){
                precunit = rst.getFloat(1);
               
                numero = rst.getString(2);
                String actualiza = "UPDATE mptabs SET precunit="+precunit+", redondeo=1 WHERE mtabus_id='"+tabu+"'"
                        + "AND numero="+numero+" AND status=1";
                Statement stactuliza = (Statement) conex.createStatement();
                stactuliza.execute(actualiza);
           

            }
             JOptionPane.showMessageDialog(rootPane, "Se han igualado los precios unitarios a los precios asumidos del listado de precios "+tabu);
        } catch (SQLException ex) {
            Logger.getLogger(recalcula.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void setprogres(int valor){
        jProgressBar1.setValue(valor);
        int porcentaje = (valor*100)/cuenta;
        String texto = valor+" partidas de "+cuenta;
        jLabel5.setText(texto);
        
    }
    public void porcaumenta(){  // SELECCIONA PRECIO UNITARIO DE LAS PARTIDAS, LE
                                // AUMENTA UN PORCENTAJE Y LO IGUALA AL PRECIO ASUMIDO
        float precunit, precasu; 
        String numero;
        
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debe insertar un porcentaje para aumentar, el campo de texto no debe estar vacio");
        }else{
        float porcentaje = Float.valueOf(jTextField1.getText());
        String consulta = "SELECT precunit,numero FROM mptabs WHERE mtabus_id='"+tabu+"' AND status=1;";
        try {
            Statement stconsulta = (Statement) conex.createStatement();
            ResultSet rstconsulta = stconsulta.executeQuery(consulta);
            while(rstconsulta.next())
            {
                precunit = rstconsulta.getFloat(1);
                numero = rstconsulta.getString(2);
                precasu = precunit * (1+porcentaje/100);
                String act = "UPDATE mptabs SET precasu ="+precasu+" WHERE numero="+numero+" AND mtabus_id='"+tabu+"' AND status=1";
                Statement stact = (Statement) conex.createStatement();
                stact.execute(act);
               
            }
             JOptionPane.showMessageDialog(rootPane, "Se ha aumentado un "+porcentaje+"% al precio unitario de las partidas y se ha igualado al precio asumido");
        } catch (SQLException ex) {
            Logger.getLogger(recalcula.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }
    public void porcdismi(){// SELECCIONA PRECIO UNITARIO DE LAS PARTIDAS, LE
                                // DISMINUYE UN PORCENTAJE Y LO IGUALA AL PRECIO ASUMIDO
        float precunit, precasu; 
        String numero;
        
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debe insertar un porcentaje para aumentar, el campo de texto no debe estar vacio");
        }else{
        float porcentaje = Float.valueOf(jTextField1.getText());
        String consulta = "SELECT precunit,numero FROM mptabs WHERE mtabus_id='"+tabu+"' AND status=1;";
        try {
            Statement stconsulta = (Statement) conex.createStatement();
            ResultSet rstconsulta = stconsulta.executeQuery(consulta);
            while(rstconsulta.next())
            {
                precunit = rstconsulta.getFloat(1);
                numero = rstconsulta.getString(2);
                precasu = precunit -(precunit * porcentaje/100);
                String act = "UPDATE mptabs SET precasu ="+precasu+" WHERE numero="+numero+" AND mtabus_id='"+tabu+"' AND status=1";
                Statement stact = (Statement) conex.createStatement();
                stact.execute(act);
               
            }
             JOptionPane.showMessageDialog(rootPane, "Se ha disminuido un "+porcentaje+"% al precio unitario de las partidas y se ha igualado al precio asumido");
        } catch (SQLException ex) {
            Logger.getLogger(recalcula.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }
    public void recalcularprecapu(){
        
        recalculasegunapu recal = new recalculasegunapu(conex, tabu,this);
        recal.start();
        
        
        
    }
    public void actualizalistado(){
        
    }
    public void borrarapus(){
        String numero;
       
        try {                
            String borradetmat = "DELETE FROM dmptabs WHERE AND mtabus_id='"+tabu+"'";
            Statement borramat = (Statement) conex.createStatement();
            borramat.execute(borradetmat);
            String borradetequip = "DELETE FROM deptabs WHERE mtabus_id='"+tabu+"'";
            Statement borraequip = (Statement) conex.createStatement();
            borraequip.execute(borradetequip);
            String borradetmano = "DELETE FROM dmoptabs WHERE mtabus_id='"+tabu+"'";
            Statement borramano = (Statement) conex.createStatement();
            borramano.execute(borradetmano);
          JOptionPane.showMessageDialog(rootPane, "Se han eliminado los ánalisis de precio unitario de las partidas del listado de precios "+tabu);

        } catch (SQLException ex) {
            Logger.getLogger(recalcula.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        jLabel4.setVisible(true);
        
        String contar = "SELECT COUNT(*) FROM mptabs WHERE mtabus_id='"+tabu+"'";
        try {
            Statement stcuenta = (Statement) conex.createStatement();
            ResultSet rstcuenta = stcuenta.executeQuery(contar);
            while(rstcuenta.next()){
                cuenta=rstcuenta.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(recalcula.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
         if(!jRadioButton6.isSelected()){
             jProgressBar1.setIndeterminate(true);
         }
        if(jRadioButton1.isSelected()){
            borraprecasu();
        }
        if(jRadioButton2.isSelected()){
            redondprecunit();
        }
        if(jRadioButton3.isSelected()){
            precasuaprecunit();
        }
        if(jRadioButton4.isSelected()){
            aumenta=Float.valueOf(jTextField1.getText().toString());
            porcaumenta();
        }
        if(jRadioButton5.isSelected()){
            dismi=Float.valueOf(jTextField2.getText().toString());
            porcdismi();
        }
        if(jRadioButton6.isSelected()){
            jProgressBar1.setIndeterminate(false);
            jProgressBar1.setMinimum(0);            
            jProgressBar1.setMaximum(cuenta);
            jProgressBar1.setVisible(true);
            recalcularprecapu();
        }
     
        if(jRadioButton8.isSelected()){
            borrarapus();
        }
      if(!jRadioButton6.isSelected()){
          
        doClose(RET_OK); 
      }// TODO add your handling code here:
    }//GEN-LAST:event_okButtonMouseClicked

private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
           
        char car = evt.getKeyChar();
        int repite = new StringTokenizer(jTextField1.getText().toString(),".").countTokens() - 1;
        if ((car<'0' || car>'9') && car!='.') {            
            evt.consume();
        }
        if(car=='.'&& repite==1){
             evt.consume();
        }
    // TODO add your handling code here:
}//GEN-LAST:event_jTextField1KeyTyped
    
    public void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
